#!/usr/bin/env python3
"""Phase 1 task 5: build tools/asset_map.csv.

Every file under unsorted-source-material/ gets exactly one row saying where it
goes under docs/ and which derivative profile applies. The 214 service-manual
scans are governed by planning/service-manual-sheet-map.csv instead and are
marked `page-map` here so the coverage check still accounts for them.

Dispositions
  publish     site asset; derivatives generated by `just derive`
  download    published as a file to download; no image derivatives
  convert     document converted to markdown in a later phase; original kept
  source-text vendor OCR text consumed by tools/import_ocr.py, not an asset
  page-map    a service-manual scan; see service-manual-sheet-map.csv
  exclude     never published (see `notes` for why)

Derivative profiles (see the plan's sizing table)
  text-page    1400px q82 preview / 2000px q82 zoom
  schematic    1600px q80 preview / native q80 zoom
  module-photo 1400px q82 preview / native q82 zoom
  photo        1400px q82 preview / native q82 zoom
  scope-trace  1400px q82 preview / native q82 zoom
  none         no derivative
"""
import csv, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = 'unsorted-source-material'

# module letter -> docs/modules/<slug>
MODULE_SLUG = {
    'A': 'a-audio-processor',   'B': 'b-rgb',              'C': 'c-video-processor',
    'D': 'd-reference-source',  'E': 'e-slide-drive',      'F': 'f-motor-sequence',
    'G': 'g-genlock',           'H': 'h-etbc-b',           'I': 'i-etbc-c',
    'J': 'j-focus',             'K': 'k-hf-processor',     'L': 'l-video-dropout-correction',
    'M': 'm-radial',            'N': 'n-display-keyboard', 'P': 'p-frontloader',
    'Q': 'q-rc5-receiver',      'R': 'r-drive-processor',  'S': 's-control',
    'T': 't-supply',            'U': 'u-analog-io',        'V': 'v-module-carrier',
    'W': 'w-cpu-data-grabber',  'X': 'x-lv-rom-decoder',   'Y': 'y-video-mixer',
    'Z': 'z-deck-electronics',
}

def slugify(name: str) -> str:
    stem, dot, ext = name.rpartition('.')
    stem = re.sub(r'[^a-z0-9]+', '-', stem.lower()).strip('-')
    return f'{stem}.{ext.lower()}'

def classify(path: str):
    """-> (disposition, dest_dir, dest_name, profile, notes)"""
    p = pathlib.Path(path)
    rel = p.relative_to(SRC)
    parts = rel.parts
    name = p.name
    top = parts[0]

    # ---- service manual scans: governed by the page map -------------------
    if top == 'vp415 service manual':
        return ('page-map', '', '', 'schematic',
                'canonical source chosen by service-manual-sheet-map.csv publish_source')

    # ---- vendor OCR -------------------------------------------------------
    if top == 'ocr-markdown-service-manual':
        if p.suffix.lower() in {'.jpeg', '.jpg'}:
            return ('exclude', '', '', 'none',
                    'downscaled by the OCR vendor; never published (manifest §3)')
        if p.suffix.lower() == '.pdf':
            return ('exclude', '', '', 'none', 'split of the deleted hires PDF; not published')
        return ('source-text', '', '', 'none', 'text source for tools/import_ocr.py')

    # ---- module photographs ----------------------------------------------
    if top == 'Module photos':
        if parts[1:2] == ('Plug in modules',):
            if re.match(r'R\w*mote control ', name):   # covers the 'Rermote' typo
                side = 'bottom' if 'bottom' in name.lower() else 'top'
                return ('publish', 'docs/modules/remote-control/assets/originals',
                        f'remote-control-{side}.jpg', 'module-photo', '')
            m = re.match(r'Module ([A-Z]) - (.+?) (top|bottom)\.jpg$', name)
            if m:
                letter, _, side = m.groups()
                slug = MODULE_SLUG[letter]
                return ('publish', f'docs/modules/{slug}/assets/originals',
                        f'{slug}-{side}.jpg', 'module-photo', '')
        if name == 'Module Layout.jpg':
            return ('publish', 'docs/system/assets/originals', 'module-layout-annotated.jpg',
                    'photo', 'annotated overhead shot naming all 18 in-situ modules')
        if name == 'Module Layout.pptx':
            return ('publish', 'docs/system/assets/originals', 'module-layout-annotated.pptx',
                    'none', 'editable source of the annotations (manifest §11.2)')
        if name == 'Module V diagram.jpg':
            return ('publish', 'docs/modules/v-module-carrier/assets/originals',
                    'module-carrier-diagram.jpg', 'photo', '')

    # ---- deck electronics (module Z) --------------------------------------
    if top == 'Module Z diagrams':
        if parts[1:2] == ('Module Z diagrams',):
            return ('publish', 'docs/reference/calibration/assets/originals',
                    slugify(f'deck-{name}'), 'scope-trace', 'deck electronics adjustment trace')
        dest = 'docs/reference/calibration/assets/originals'
        prof = 'none' if p.suffix.lower() == '.pptx' else 'photo'
        note = 'editable source (manifest §11.2)' if prof == 'none' else 'annotated potentiometer photo'
        return ('publish', dest, slugify(name), prof, note)

    # ---- exterior photographs --------------------------------------------
    if top == 'Pictures':
        return ('publish', 'docs/overview/assets/originals', slugify(name), 'photo',
                'exterior photograph - chapter 1 controls and connections')
    if top == 'title picture.jpg' or name == 'title picture.jpg':
        return ('publish', 'docs/assets/originals', 'title-picture.jpg', 'photo',
                'landing page hero image')

    # ---- disassembly guide -------------------------------------------------
    if top == 'Disassembly guide':
        if parts[1:2] == ('PNG',) and name.startswith('vp415-colour300dpi'):
            return ('publish', 'docs/general-service/assets/originals', slugify(name),
                    'schematic',
                    'cropped 2048px derivative of a manual page - the crop is editorial '
                    'work worth keeping (manifest §11.2)')
        prof = 'schematic' if p.suffix.lower() == '.png' else 'photo'
        return ('publish', 'docs/general-service/assets/originals', slugify(name), prof,
                'demounting / exploded view')

    # ---- repair case studies and RGB calibration --------------------------
    if top == 'VP415 repair':
        if parts[1:2] == ('RGB Module calibration',):
            dest = 'docs/reference/calibration/assets/originals'
            if p.suffix.lower() == '.docx':
                return ('convert', dest, slugify(name), 'none',
                        'converted to docs/reference/calibration/rgb-module.md in phase 6')
            if p.suffix.lower() == '.pptx':
                return ('publish', dest, slugify(name), 'none', 'editable source (manifest §11.2)')
            return ('publish', dest, slugify(name), 'scope-trace', 'RGB calibration capture')
        # error-7 lives in the '7' subfolder, error-9 at the top level
        study = 'error-7-focus' if parts[1:2] == ('7',) else 'error-9-frame-lock'
        dest = f'docs/repair/case-studies/assets/originals'
        if p.suffix.lower() == '.docx':
            return ('convert', dest, slugify(name), 'none',
                    f'converted to docs/repair/case-studies/{study}.md in phase 6')
        return ('publish', dest, slugify(f'{study}-{name}'), 'scope-trace',
                f'scope trace for the {study} investigation')

    # ---- firmware ----------------------------------------------------------
    if top in ('VP415 ROM dumps', 'Microcontroller dumps'):
        if p.suffix.lower() == '.zip':
            return ('exclude', '', '', 'none', 'contents already present unpacked (manifest §11.1)')
        if p.suffix.lower() == '.pdf':
            return ('download', 'docs/reference/assets/originals/datasheets', slugify(name),
                    'none', 'device datasheet')
        if p.suffix.lower() in ('.png', '.jpg'):
            return ('publish', 'docs/reference/assets/originals', slugify(name), 'photo',
                    'ROM version survey')
        if p.suffix.lower() == '.txt':
            return ('convert', 'docs/reference/assets/originals', slugify(name), 'none',
                    'provenance note quoted on the firmware page')
        return ('download', 'docs/reference/assets/originals/firmware',
                str(rel).replace('/', '_'), 'none',
                'checksums in planning/firmware-checksums.csv; 28 files, 11 distinct images')

    # ---- misc reference ----------------------------------------------------
    if top == 'misc':
        if name == 'vp415Fcode.xlsx':
            return ('convert', 'docs/reference/assets/originals', slugify(name), 'none',
                    'becomes the searchable F-code table in docs/reference/f-codes.md')
        if p.suffix.lower() == '.docx':
            return ('convert', 'docs/reference/assets/originals', slugify(name), 'none',
                    'real-player ?D/?P/?U/?= responses -> docs/reference/f-codes.md')
        if name == 'MB88303-Fujitsu.pdf':
            return ('download', 'docs/reference/assets/originals/datasheets', slugify(name),
                    'none', 'device datasheet')
        return ('download', 'docs/reference/assets/originals', slugify(name), 'none',
                'duplicate of the docx in PDF form')

    # ---- operating instructions -------------------------------------------
    if top == 'pdfs':
        if 'uncompressed' in name:
            return ('exclude', '', '', 'none',
                    'superseded by the compressed PDF plus the 27 page scans (manifest §11.1)')
        return ('download', 'docs/operating-instructions/assets/originals',
                'philips-vp415-operating-instructions.pdf', 'none', 'user manual, 8 sections')
    if top == 'vp415 manual':
        m = re.match(r'image(\d+)', name)
        n = int(m.group(1)) if m else 0
        return ('publish', 'docs/operating-instructions/assets/originals',
                f'operating-instructions-scan-{n:02d}.jpg', 'text-page',
                '3500x4956 page scan of the operating instructions')

    return ('UNMAPPED', '', '', 'none', 'no rule matched - fix build_asset_map.py')


def main():
    inv = {r['path']: r for r in csv.DictReader(open(ROOT/'planning/source-inventory.csv'))}
    on_disk = sorted(str(p.relative_to(ROOT)) for p in (ROOT/SRC).rglob('*') if p.is_file())

    out = ROOT/'tools/asset_map.csv'
    counts, unmapped = {}, []
    with open(out, 'w', newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['path', 'bytes', 'width', 'height', 'disposition',
                    'dest_dir', 'dest_name', 'profile', 'notes'])
        for path in on_disk:
            disp, dd, dn, prof, notes = classify(path)
            if disp == 'UNMAPPED':
                unmapped.append(path)
            rec = inv.get(path, {})
            w.writerow([path, rec.get('bytes', ''), rec.get('width', ''), rec.get('height', ''),
                        disp, dd, dn, prof, notes])
            counts[disp] = counts.get(disp, 0) + 1

    print(f'{sum(counts.values())} files -> {out.relative_to(ROOT)}')
    for k in sorted(counts):
        print(f'  {counts[k]:5d}  {k}')
    if unmapped:
        print(f'\nUNMAPPED ({len(unmapped)}):')
        for u in unmapped[:40]:
            print('  ', u)
    else:
        print('\nevery file is accounted for')

if __name__ == '__main__':
    main()
